CREATE TABLE WEEK11_13_MONTHS
	(`DATE` VARCHAR(50));
    
INSERT INTO WEEK11_13_MONTHS VALUES
	('1st January'),
    ('31st December');

UPDATE week11_13_months
SET `DATE` = str_to_date(CONCAT(`DATE`,' 2024'), "%D %M %Y");

###############################################################

WITH RECURSIVE SCAFFOLD AS (
	SELECT 
		(SELECT MIN(`DATE`) FROM week11_13_months) AS MIN_DATE,
		1 AS NEW_DAY,
		1 AS NEW_MONTH
			UNION ALL
	SELECT
		date_add(MIN_DATE, INTERVAL 1 DAY) AS MIN_DATE,
        CASE WHEN NEW_DAY=28 THEN 1 ELSE NEW_DAY+1 END AS NEW_DAY,
        CASE WHEN NEW_DAY=28 THEN NEW_MONTH+1 ELSE NEW_MONTH END AS NEW_MONTH
	FROM SCAFFOLD
		WHERE MIN_DATE<(SELECT MAX(`DATE`) FROM week11_13_months)
	)
    
SELECT 
	MIN_DATE AS ORIGINAL_DATE, 
    CONCAT('2024-',
			CASE WHEN LENGTH(NEW_MONTH)=1 THEN CONCAT('0',NEW_MONTH) ELSE NEW_MONTH END,
            '-',
			CASE WHEN LENGTH(NEW_DAY)=1 THEN CONCAT('0',NEW_DAY) ELSE NEW_DAY END
			) AS NEW_DATE
FROM SCAFFOLD
	HAVING LEFT(ORIGINAL_DATE,7) != LEFT(NEW_DATE,7);
