CREATE TABLE WEEK12_UNDERGRAD_LOANS
	(  LOAN_TYPE VARCHAR(20),
     COURSE_START VARCHAR(20),
     COURSE_LENGTH INT,
     AMOUNT_PER_YEAR DOUBLE
  );

INSERT INTO WEEK12_UNDERGRAD_LOANS VALUES
	('Tuition Fees', 'September 2020', 3, 9250),
  ('Maintenance', 'September 2020', 3, 5820);

UPDATE WEEK12_UNDERGRAD_LOANS
  SET COURSE_START = STR_TO_DATE(CONCAT('01 ',COURSE_START), '%d %M %Y');

CREATE TABLE WEEK12_REPAYMENT
	( LOAN VARCHAR(20),
	  INTEREST VARCHAR(10),
    REPAYMENT_THRESHOLD DOUBLE,
    PERCENT_REPAYMENT_OVER_THRESHOLD DOUBLE
  );

INSERT INTO WEEK12_REPAYMENT VALUES
	('Undergraduate', '7.70%', 27295,9),
  ('Postgraduate', '7.70%', 21000,6);

#############################################
SET @SALARY = 35000
#############################################
	
WITH RECURSIVE SCAFFOLD AS(
	SELECT
    *,
    COURSE_START AS PAYMENT_DATE
	FROM WEEK12_UNDERGRAD_LOANS
		UNION ALL
	SELECT 
		LOAN_TYPE,
    COURSE_START,
    COURSE_LENGTH,
    AMOUNT_PER_YEAR,
    DATE_ADD(PAYMENT_DATE, INTERVAL 1 YEAR) AS PAYMENT_DATE
	FROM SCAFFOLD
		WHERE PAYMENT_DATE<DATE_ADD(COURSE_START, INTERVAL 2 YEAR)
),
FULL_TABLE AS(
	SELECT 
		LOAN_TYPE, 
		AMOUNT_PER_YEAR, 
		PAYMENT_DATE, 
		LOAN, 
		CAST(INTEREST AS DOUBLE)/100 AS INTEREST,  
    REPAYMENT_THRESHOLD, 
		PERCENT_REPAYMENT_OVER_THRESHOLD/100 AS PERCET_REPAYMENT_OVER_THRESHOLD,
		TIMESTAMPDIFF(MONTH, PAYMENT_DATE, '2024-04-01') as INTEREST_MONTHS 
	FROM SCAFFOLD
		CROSS JOIN WEEK12_REPAYMENT
			WHERE LOAN='Undergraduate'
), 
FINAL_TABLE AS(
	SELECT 
		@SALARY,
		LOAN,
    INTEREST,
    REPAYMENT_THRESHOLD,
    PERCET_REPAYMENT_OVER_THRESHOLD,
    SUM(AMOUNT_PER_YEAR) AS AMOUNT_BORROWED,
		SUM(AMOUNT_PER_YEAR *(
						POW((1+ (0.077/12)),
						((INTEREST_MONTHS/12)*12)))
				) AS AMOUNT_AND_INTEREST
	FROM FULL_TABLE
		GROUP BY @SALARY, LOAN, INTEREST, REPAYMENT_THRESHOLD, PERCET_REPAYMENT_OVER_THRESHOLD)
  
SELECT 
	ROUND(((@SALARY-REPAYMENT_THRESHOLD)*PERCET_REPAYMENT_OVER_THRESHOLD)/12,2) AS MONTHYLY_REPAYMENT,
  AMOUNT_BORROWED,
  ROUND(AMOUNT_AND_INTEREST,2) AS AMOUNT_PLUS_INTEREST,
  ROUND((AMOUNT_AND_INTEREST-(((@SALARY-REPAYMENT_THRESHOLD)*PERCET_REPAYMENT_OVER_THRESHOLD)/12) )*0.077/12,2) AS ADDITIONAL_INTEREST_NEXT_MONTH
FROM FINAL_TABLE;
