-- FUNCTIONS USED 
-- CREATE TABLE, INSERT INTO, CTE, STR_TO_DATE, CAST, CONCAT, RIGHT, LEFT, CURDATE, SUM, CASE, TRIM, TRAILING.

-- CREATE TABLES AND INPUT DATA.
CREATE TABLE COUPLES 
	(COUPLE	VARCHAR(512), RELATIONSHIP_START VARCHAR(512));
INSERT INTO COUPLES VALUES(); 
    
CREATE TABLE GIFTS 
	(`YEAR` VARCHAR(512), GIFT VARCHAR(512));
INSERT INTO GIFTS VALUES();   

-- Calculate the total number of valentines each couple has been together

CREATE TABLE TOTAL_YEARS_TOGETHER
 WITH CTE AS(
        SELECT COUPLE, 
			  RELATIONSHIP_START,
	      STR_TO_DATE(relationship_start, "%M %d, %Y") as DATE_RELATIONSHIP_START,
        CAST(CONCAT(CAST(RIGHT(RELATIONSHIP_START,4) AS char), "-02-14") AS DATE) AS VALENTINES,
        CURDATE() AS TODAY
        FROM COUPLES)
    SELECT 
	    COUPLE, 
        RELATIONSHIP_START,
        DATE_RELATIONSHIP_START,
        SUM(
          -- THE CURRENT YEAR
          LEFT(TODAY,4) 
          -- MINUS THE YEAR THE COUPLE GOT TOGETHER, GIVES US THE NUMBER OF YEARS TOGETHER.
          - CAST(RIGHT(RELATIONSHIP_START, 4) AS DOUBLE)
          -- IF THE COUPLE GOT TOGETHER BEFORE VALENTINES IN THE FIRST YEAR, THEY HAVE HAD AN ADDITIONAL VALENTINES TOGETHER. 
          + (CASE WHEN DATE_RELATIONSHIP_START<VALENTINES THEN 1 ELSE 0 END)
        ) AS VALENTINES_TOGETHER
    FROM CTE
    GROUP BY COUPLE, DATE_RELATIONSHIP_START, RELATIONSHIP_START;

-- JOIN GIFTS TABLE TO FIND GIFT SUGGESTIONS. 

SELECT
	  COUPLE, 
    DATE_RELATIONSHIP_START, 
    VALENTINES_TOGETHER, 
    GIFT
FROM TOTAL_YEARS_TOGETHER
JOIN GIFTS 
	ON VALENTINES_TOGETHER =  
  -- REMOVE THE TRAILING LETTERS FROM THE YEAR (I.E. ST, ND).
  CAST(TRIM(TRAILING RIGHT(`YEAR`,2) FROM `YEAR`) AS DECIMAL);
