-- FUNCTIONS USED:
-- CREATE TABLE, CREATE VIEW, INSERT INTO, UPDATE, SET, STR_TO_DATE, CASE, CTE, IFNULL, COUNT, SUM, RIGHT & LEFT JOIN

-- CREATE TABLES AND INSERT DATA.
CREATE TABLE WEEK8_ACTIONS 
(
    FLIGHT_NUMBER	VARCHAR(512),
    FLIGHT_DATE		VARCHAR(512),
    CUSTOMER_ID		VARCHAR(512),
    ACTION		VARCHAR(512),
    DATE		VARCHAR(512),
    CLASS		VARCHAR(512),
    ROW_		VARCHAR(512),
    SEAT		VARCHAR(512)
);
INSERT INTO WEEK8_ACTIONS VALUES ();
	
CREATE TABLE WEEK8_DETAILS 
(
    FLIGHT_NUMBER 	VARCHAR(512),
    FLIGHT_DATE 	VARCHAR(512),
    CLASS 		VARCHAR(512),
    CAPACITY 		INT
);

INSERT INTO WEEK8_DETAILS VALUES ();

############################################################################################
-- CHANGE DATE FORMATTING OF INSERTED DATA
UPDATE week8_details
    SET `FLIGHT_DATE`=STR_TO_DATE(`FLIGHT_DATE`,'%m/%d/%yy');

############################################################################################
-- FILTERING THE DATA TO REMOVE ANY CANCLLED BOOKINGS AND ONLY KEEP THE MOST RECENT ROW. 
CREATE VIEW WEEK8_MOST_RECENT_UPDATES_LIST AS
WITH CTE AS 
	(SELECT 
    		*,
		-- CREATE BOOLEAN FOR WHETHER OR NOT A FLIGHT HAS BEEN CANCELLED
    		CASE WHEN ACTION="Cancelled" THEN 1 ELSE 0 END AS FLIGHT_CANCELLED 
  	FROM WEEK8_ACTIONS),
-- SECOND CTE FINDS THE MOST RECENT UPDATE FOR EACH BOOKING.
CTE2 AS 
  	(SELECT 
    		FLIGHT_NUMBER, 
    		FLIGHT_DATE, 
    		CUSTOMER_ID, 
    		MAX(DATE) AS MOST_RECENT 
 	FROM CTE 
 	GROUP BY FLIGHT_NUMBER, FLIGHT_DATE, CUSTOMER_ID)

-- UTILIZE THE CTE'S TO GENERATE A LIST OF THE MOST RECENT UPDATES TO FLIGHT BOOKINGS - THAT HAVENT BEEN CANCELLED. 
SELECT 
  A.*,
  IFNULL(FLIGHT_CANCELLED,0) AS CANCELLED,
  C.MOST_RECENT
FROM WEEK8_ACTIONS AS A
LEFT JOIN CTE AS B 
    	ON A.FLIGHT_NUMBER = B.FLIGHT_NUMBER
        AND A.FLIGHT_DATE = B.FLIGHT_DATE
        AND A.CUSTOMER_ID = B.CUSTOMER_ID
        AND FLIGHT_CANCELLED = 1
LEFT JOIN CTE2 C 
    	ON A.FLIGHT_NUMBER = C.FLIGHT_NUMBER
        AND A.FLIGHT_DATE = C.FLIGHT_DATE
        AND A.CUSTOMER_ID = C.CUSTOMER_ID
-- FILTER TO REMOVE CANCELLED FLIGHTS AND ONLY HAVE THE MOST RECENT UPDATED ROW IN THE DATA BASE.
WHERE IFNULL(FLIGHT_CANCELLED,0)=0
	AND A.DATE = C.MOST_RECENT;

-- CTE COUNTS THE NUMBER OF SEATS BOOKED AT EACH DATE 
WITH CTE AS (
  SELECT 
    A.FLIGHT_NUMBER, 
    A.FLIGHT_DATE,
    A.CLASS, 
    A.CUSTOMER_ID, 
    A.ACTION,
    A.DATE, 
    A.ROW_, 
    A.SEAT,
    COUNT(B.CUSTOMER_ID) AS TOTAL_SEATS_BOOKED_OVER_TIME
  FROM WEEK8_MOST_RECENT_UPDATES_LIST A 
  LEFT JOIN WEEK8_MOST_RECENT_UPDATES_LIST B 
	ON A.FLIGHT_NUMBER = B.FLIGHT_NUMBER
        AND A.FLIGHT_DATE = B.FLIGHT_DATE
        AND A.CLASS = B.CLASS
        AND A.DATE >= B.DATE
  GROUP BY A.FLIGHT_NUMBER, A.FLIGHT_DATE, A.CUSTOMER_ID, A.ACTION, A.DATE, A.CLASS, A.ROW_, A.SEAT
  ORDER BY A.FLIGHT_NUMBER, A.FLIGHT_DATE, A.CLASS, A.DATE)

SELECT 
  B.FLIGHT_NUMBER, 
  B.FLIGHT_DATE, 
  B.CLASS, 
  IFNULL(TOTAL_SEATS_BOOKED_OVER_TIME,0) AS TOTAL_SEATS_BOOKED_OVER_TIME, 
  CAPACITY, 
  IFNULL(SUM(TOTAL_SEATS_BOOKED_OVER_TIME/CAPACITY)*100,0) AS CAPACITY_PERCENT, 
  IFNULL(CUSTOMER_ID,"") AS CUSTOMER_ID,
  IFNULL(ACTION,"") AS ACTION,
  IFNULL(DATE,"2024-02-28") AS DATE, 
  IFNULL(ROW_,"") AS `ROW`,
  IFNULL(SEAT,"") AS SEAT
FROM CTE AS A 
RIGHT JOIN WEEK8_DETAILS AS B
	ON A.FLIGHT_NUMBER = B.FLIGHT_NUMBER
      	AND A.FLIGHT_DATE = B.FLIGHT_DATE
     	AND A.CLASS = B.CLASS 
GROUP BY B.FLIGHT_NUMBER, B.FLIGHT_DATE, B.CLASS, TOTAL_SEATS_BOOKED_OVER_TIME, CAPACITY, CUSTOMER_ID, ACTION, DATE, ROW_, SEAT
ORDER BY B.FLIGHT_NUMBER, B.FLIGHT_DATE, B.CLASS, TOTAL_SEATS_BOOKED_OVER_TIME;
