-- FUNCTIONS USED:
-- CREATE TABLE, CREATE VIEW, CONCAT, LEFT, MID, LOCATE, SUM, UNION, INSERT INTO, CTE, MONTH, CASE/WHEN, JOIN, GROUP BY

-- Create our four targets tables
	CREATE TABLE WEEK3_Q1_TARGETS 
		(`MONTH` TEXT, 
		 `CLASS` TEXT, 
		 `TARGET` INT);

	CREATE TABLE WEEK3_Q2_TARGETS 
		(`MONTH` TEXT, 
		 `CLASS` TEXT, 
		 `TARGET` INT);

	CREATE TABLE WEEK3_Q3_TARGETS 
		(`MONTH` TEXT, 
		 `CLASS` TEXT, 
		 `TARGET` INT);
		 
	CREATE TABLE WEEK3_Q4_TARGETS 
		(`MONTH` TEXT, 
		 `CLASS` TEXT, 
		 `TARGET` INT);

-- insert the values into our tables
	INSERT INTO WEEK3_Q1_TARGETS 
	VALUES (?,?,?,?);

	INSERT INTO WEEK3_Q2_TARGETS
	VALUES (?,?,?,?);

	INSERT INTO WEEK3_Q3_TARGETS
	VALUES (?,?,?,?);
		
	INSERT INTO WEEK3_Q4_TARGETS
	VALUES (?,?,?,?);

	CREATE TABLE `week3_unioned_output` AS
	WITH CTE AS 
		(SELECT 
			*
		FROM `prep2024_w1`.`week1_output_no`
			UNION ALL
		SELECT 
			*
		FROM `prep2024_w1`.`week1_output_yes`)
-- end cte
	SELECT
		month(DATE) AS MONTH, 
		CASE 
			WHEN CLASS="First Class" THEN "ECONOMY"
			WHEN CLASS="Business Class" THEN "PREMIUM_ECONOMY"
			WHEN CLASS="Premium Economy" THEN "BUSINESS_CLASS"
			WHEN CLASS="Economy" THEN "FIRST_CLASS"
			END AS CLASS,
		FLOW_CARD,
		PRICE
	FROM CTE;

	CREATE VIEW WEEK3_FLIGHTINFO AS
	SELECT
		MONTH,
		CONCAT(
			LEFT(CLASS,1),
			MID(CLASS,
				(CASE WHEN LOCATE("_",CLASS)="" 
				THEN LOCATE("_",CLASS)
				ELSE LOCATE("_",CLASS)+1
				END) 
				,1)) 
			AS CLASSCONCAT, 
		SUM(PRICE) AS PRICE
	FROM week3_unioned_output
	GROUP BY CLASSCONCAT, MONTH;

-- UNION QUARTER TARGETS
	CREATE VIEW WEEK3_TARGETS AS
	SELECT * FROM week3_q1_targets	
		UNION ALL
	SELECT * FROM week3_q2_targets	
		UNION ALL
	SELECT * FROM week3_q3_targets	
		UNION ALL
	SELECT * FROM week3_q4_targets;

-- CREATE FINAL OUPUT
	CREATE VIEW WEEK3_OUTPUT AS
	SELECT
		A.MONTH AS DATE,
		B.CLASS,
		A.PRICE,
		B.TARGET,
		SUM(B.TARGET-A.PRICE) AS DIFFERENCE_TO_TARGET
	FROM week3_flightinfo AS A
		JOIN WEEK3_TARGETS AS B
			ON A.MONTH = B.MONTH AND A.CLASSCONCAT = B.CLASS
	GROUP BY DATE, B.CLASS, A.PRICE, B.TARGET;
