-- CREATE TABLES 
  CREATE TABLE WEEK5_TICKET_SALES
  	(`DATE` DATE, `FLIGHT_NUMBER` TEXT, `CUSTOMER_ID` TEXT, `PRICE` DOUBLE);
  
  CREATE TABLE WEEK5_FLIGHTS_2024 
  	(`DATE` DATE, `FLIGHT_NUMBER` TEXT, `FROM` TEXT, `TO` TEXT);
  
  CREATE TABLE WEEK5_CUSTOMERS
  	(`CUSTOMER_ID` TEXT, `LAST_DATE_FLOWN` DATE, `FIRST_NAME` TEXT, `LAST_NAME` TEXT, `EMAIL` TEXT, `GENDER` TEXT);

-- INSERT DATA INTO TABLES
  INSERT INTO WEEK5_TICKET_SALES VALUES (?, ?, ?, ?);  
  INSERT INTO WEEK5_FLIGHTS_2024 VALUES (?, ?, ?, ?);
  INSERT INTO WEEK5_CUSTOMERS VALUES (?, ?, ?, ?);

-- FOR THE FIRST OUTPUT:
CREATE VIEW WEEK5_OUTPUT1_2024_BOOKED_CUSTOMER_DETAILS AS
  SELECT 
    A.DATE,
    A.FLIGHT_NUMBER,
    A.FROM,
    A.TO,
    B.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    C.GENDER,
    C.EMAIL,
    PRICE
  FROM WEEK5_FLIGHTS_2024 AS A
  	JOIN WEEK5_TICKET_SALES AS B
  		ON A.DATE=B.DATE 
      AND A.FLIGHT_NUMBER=B.FLIGHT_NUMBER
  	JOIN WEEK5_CUSTOMERS AS C
  		ON B.CUSTOMER_ID = C.CUSTOMER_ID
  WHERE A.DATE BETWEEN '2023-12-31' AND '2024-12-31';

-- FOR THE SECOND OUTPUT
CREATE VIEW WEEK5_OUTPUT2_2024_UNBOOKED_FLIGHTS AS
  SELECT
  	CURDATE() AS TODAY,
    A.FLIGHT_NUMBER,
    A.FROM,
    A.TO,
    A.DATE
  FROM WEEK5_FLIGHTS_2024 AS A
  	LEFT JOIN WEEK5_TICKET_SALES AS B
  		ON A.FLIGHT_NUMBER = B.FLIGHT_NUMBER
      AND A.DATE = B.DATE
  WHERE B.FLIGHT_NUMBER IS NULL;

-- FOR THE THIRD OUTPUT
CREATE VIEW WEEK5_OUTPUT3_CUSTOMER_BOOKING_CATEGORISATION AS
  SELECT
  	A.CUSTOMER_ID,
    LAST_DATE_FLOWN,
    DATEDIFF(CURDATE(), LAST_DATE_FLOWN) AS DAYS_SINCE_LAST_FLOWN,
  	TIMESTAMPDIFF(MONTH, LAST_DATE_FLOWN, CURDATE()) AS MONTHS,
    (CASE 
  		WHEN TIMESTAMPDIFF(MONTH, LAST_DATE_FLOWN, CURDATE()) <=3 THEN "RECENT FLIERS" 
  		WHEN TIMESTAMPDIFF(MONTH, LAST_DATE_FLOWN, CURDATE()) BETWEEN 3 AND 6 THEN "TAKING A BREAK" 
      WHEN TIMESTAMPDIFF(MONTH, LAST_DATE_FLOWN, CURDATE()) BETWEEN 6 AND 9 THEN "BEEN AWAY A WHILE" 
  		WHEN TIMESTAMPDIFF(MONTH, LAST_DATE_FLOWN, CURDATE()) >9 THEN "LAPSED CUSTOMERS" 
  	END) AS CATEGORY,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    GENDER
  FROM WEEK5_CUSTOMERS AS A
  	LEFT JOIN WEEK5_TICKET_SALES AS B
  		ON A.CUSTOMER_ID=B.CUSTOMER_ID
  WHERE B.DATE IS NULL;
